### ISSUE TITLE
Bug: Navbar is transparent while scrolling

### ISSUE THREAD

**Issue by thatsuman** [TeamOpencampus/opencampus-website#17]
- Make its background white while scrolling
![image](https://user-images.githubusercontent.com/56498881/195140937-fc9b5c1f-b386-401e-a6f9-93a875b1c35d.png)

**Comment by syprogrammer** [comment]
can you assign me this

**Comment by jsvigneshkanna** [comment]
@thatsuman ,
Please assign this issue to my name, I have done this similar implementation in my portfolio

**Comment by thatsuman** [comment]
Okay! Assigning you @jsvigneshkanna 

Update: Hey, @jsvigneshkanna Sorry I didn't see someone commented earlier. As first-come-first-serve rule I'm assigning to @syprogrammer .

**Comment by Devesh326** [comment]
Hey @thatsuman I would like to solve and contribute to this issue!

**Comment by Devesh326** [comment]
#19 @thatsuman Have made the PR!

**Comment by thatsuman** [comment]
> #19 @thatsuman Have made the PR!

I've assigned this issue to someone. 
If you have any suggestions or would like to add any feature please make a issue, we'll discuss there.

**Comment by Ashwani-de** [comment]
Assign me this issue

**Comment by syprogrammer** [comment]
@thatsuman i have fixed it now it look like this check if it is ok : https://bit.ly/3RMEooM

**Comment by thatsuman** [comment]
> @thatsuman i have fixed it now it look like this check if it is ok : https://bit.ly/3RMEooM

Seems good. Please make a PR so that I can review the changes.

**Comment by syprogrammer** [comment]
@thatsuman  i have made PR review it
