### ISSUE TITLE
To change nav links when at respective section.

### ISSUE THREAD

**Issue by Devesh326** [TeamOpencampus/opencampus-website#21]
When the page is scrolled to a particular section the navbar link will change its color to blue.

**Comment by Devesh326** [comment]
Hey @thatsuman I would like to work on this issue!

**Comment by thatsuman** [comment]
Yeah that would be cool. You can work on this.

**Comment by Devesh326** [comment]
#23 Hey @thatsuman have solved the issue and made the PR.

**Comment by Devesh326** [comment]
I had a question, would this PR be considered in hactoberfest 2022?
Thanks!

**Comment by thatsuman** [comment]
> I had a question, would this PR be considered in hactoberfest 2022? Thanks!

Yes, This issue is tagged with Hactoberfest label.
Thanks for your contribution
