### ISSUE TITLE
Enhancing the UI of Footer

### ISSUE THREAD

**Issue by Mahak008** [TeamOpencampus/opencampus-website#24]
Kindly assign this issue to me.

**Comment by thatsuman** [comment]
Do you have any preferred design or how would you like to enhance the UI?

**Comment by Harsh-garg-coder** [comment]
i have some enhancements : 
1. can change the color of link to something attractive on hover.
2. can add bottom-border to each link of footer.
3. can add responsiveness to the footer(by alligning the link to the center in smaller screens).

**Comment by thatsuman** [comment]
> i have some enhancements : 
> 1. can change the color of link to something attractive on hover.
> 2. can add bottom-border to each link of footer.
> 3. can add responsiveness to the footer(by alligning the link to the center in smaller screens).

Okay sounds good.
Also please do the needful changes for dark theme as well. 

Assigning you.

**Comment by Harsh-garg-coder** [comment]
ok @thatsuman
