### ISSUE TITLE
Feat: Implement dark theme for website

### ISSUE THREAD

**Issue by thatsuman** [TeamOpencampus/opencampus-website#26]
- Create a separate folder named `dark-theme` under root folder and implement dark theme there
- Site contents should be clear enough to read and change the font colour of headings, paragraphs etc. if necessary for dark theme
- Create a toggle button and implement logic to enable or disable dark theme on top right corner of navbar
- Creativity is welcome

**Comment by Anuran12** [comment]
@thatsuman I would like to work on this

**Comment by thatsuman** [comment]
> @thatsuman I would like to work on this

Sure

**Comment by aliendostea** [comment]
@thatsuman I did a PR for this issue

**Comment by thatsuman** [comment]
> @thatsuman I did a PR for this issue

Currently @Anuran12 is working on this issue.
Thanks for showing interest to contribute on this project.

**Comment by Anuran12** [comment]
@aliendostea yea.. i am on the half way ?
