### ISSUE TITLE
Add FAQ Section

### ISSUE THREAD

**Issue by thatsuman** [TeamOpencampus/opencampus-website#4]
- Make a suitable FAQ Accordion for the website 
- Put some dummy texts as a faq answers for now
- Creativity is welcome
### Inspirations: 
- https://kiranworkspace.com/downloads/faq-ui-design-html-css/ 
- https://codemyui.com/faq-content-style-accordion/   
### FAQ Questions are:
- What is OpenCampus?
- How to Join OpenCampus?
- Benefits of Joining OpenCampus for Students?
- Benefits of Joining OpenCampus for Institutions?

**Comment by priyanshumaitra** [comment]
Could you assign me into this issue? I wanna work on this. Thanks.

**Comment by thatsuman** [comment]
> Could you assign me into this issue? I wanna work on this. Thanks.

Sure, go ahead!
